fix: use fullmatch instead of search for MatchOperator
dialoguemd/pypred pull request #4
Opened 2021-05-13 19:01 UTC by GuillaumeTech

## Description

The match operator of pypred uses .search, it should use .fullmatch
.search: look if the regex is matched somewhere in the string
.fullmatch: look the if the whole string matches the regex

this is causing weird behavior when using the botsdk 
`Condition('test matches "[A-Za-z]+"').evaluate({"test": "we./weifj fwifweo"})) ` this should evalute to `False` but it evaluate to `True`

a quick recording showing the issue:
https://user-images.githubusercontent.com/27060431/118173188-3e667f80-b3fb-11eb-84e6-428b00fec118.mov

Is there flows in BM that were relying on the .search behavior, and that could break with this change ?

## Related changes
The validation of slots is not working on: https://github.com/dialoguemd/botfront/pull/17

## Checklist

- [x] PR title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) guidelines 
- [x] All relevant PR sections are populated, irrelevant ones are removed

2021-05-13 19:15 UTC, arththebird commented
Should we just update the condition to be `Condition('test matches "^[A-Za-z]+$"')`?

2021-05-13 19:19 UTC, arththebird requested changes
If we really want to update the behavior (which I'm not sure we should as there's a way to have the same result if needed):

- Please paste the output of tests in the PR to make sure that they still pass (`make test`)
- Make sure that we don't lower the coverage
- Add tests cases to `tests/integ/preds.txt` for cases that should pass and fail
- Create an associated PR to update `dialogue.botsdk.actions` to this version of the lib to make sure that it still works
- Then create an associated PR to update BM to the version of `dialogue.botsdk.actions` above and make sure that tests still pass

Thank you!

2021-05-13 19:24 UTC, arththebird commented
@edouardlp What's your take on this?

2021-05-13 19:31 UTC, GuillaumeTech commented
Yes that does work, but it's a bit odd that "matches" is not really a match behind the scene, If it can affect BM it would be easier to stick to the current behavior, otherwise I think it would be nice to remove the ambiguity

2021-05-13 20:50 UTC, arththebird commented
> Yes that does work, but it's a bit odd that "matches" is not really a match behind the scene, If it can affect BM it would be easier to stick to the current behavior, otherwise I think it would be nice to remove the ambiguity

So the rationale for keeping it the way it is now is:

We were planning to merging the changes in that fork upstream (at some point when we can liberate capacity for it in sprint). If we change this to `fullmatch`, we most probably won't be able to, since it a huge breaking change that will affect all people using the lib.

But most importantly, it is because we remove a feature if we use `fullmatch`. There's no way, AFAIK, to have the current behavior with `fullmatch`, where as it's possible to have the behavior of `fullmatch` with the current implementation by simply adding `^` and `$` to the regex. In the end, `fullmatch` just appends the `^` and `$` characters to the regex.

Finally, `pypred` is compatible with python 2.7, 3.4, 3.5 and up. `fullmatch` was introduced in python 3.4, so if we start using it, we remove compatibility with python 2.7. Not that it's a big deal for Dialogue, but it re-enforce the fact that we won't be able to merge the fork upstream.

2021-05-14 12:45 UTC, GuillaumeTech commented
okok, I agree that too much consequences for that small of a change

2021-05-14 12:45 UTC, closed without merging